# Generated by Django 5.0.8 on 2024-09-18 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('partner', 'Partner'), ('owner', 'Owner')], default='partner', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to='institutions.institutionpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'institution')},
            },
        ),
        migrations.AddField(
            model_name='institutionpage',
            name='institution_memberships',
            field=models.ManyToManyField(blank=True, related_name='institutions', through='institutions.InstitutionMembership', to=settings.AUTH_USER_MODEL, verbose_name='Socios'),
        ),
    ]
