# Generated by Django 5.0.8 on 2024-09-04 19:40

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_datasetpage_url_dataset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='description',
            field=wagtail.fields.RichTextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='datadictionary',
            name='description',
            field=wagtail.fields.RichTextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='datadictionary',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='datadictionary',
            name='unit',
            field=models.CharField(max_length=100, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='citation',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Citación'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='description',
            field=wagtail.fields.RichTextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='institution_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='home.institutionpage', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='keywords',
            field=models.TextField(blank=True, help_text='Agregar múltiples palabras clave separadas por comas', verbose_name='Palabras clave'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='type_dataset',
            field=models.CharField(choices=[('public', 'Público'), ('restricted', 'Restringido')], max_length=50, verbose_name='Acceso'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='upload_frequency',
            field=models.CharField(blank=True, choices=[('hourly', 'Horario'), ('daily', 'Diaria'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannually', 'Semestral')], max_length=20, verbose_name='Frecuencia de subida'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='url_dataset',
            field=models.URLField(blank=True, verbose_name='URL del dataset'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='municipality_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre municipalidad'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre región'),
        ),
        migrations.AlterField(
            model_name='institutionpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='institutionpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='institutionpage',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='Representante principal'),
        ),
        migrations.AlterField(
            model_name='institutionpage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='institutionpage',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
    ]
