# Generated by Django 5.0.8 on 2024-09-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_additionalinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpage',
            name='keywords',
            field=models.CharField(blank=True, choices=[('clima', 'Clima'), ('cultivos', 'Cultivos'), ('temperatura', 'Temperatura'), ('precipitacion', 'Precipitación'), ('humedad', 'Humedad'), ('evapotranspiracion', 'Evapotranspiración'), ('radiacion_solar', 'Radiación Solar'), ('productividad_agricola', 'Productividad Agrícola'), ('fenologia', 'Fenología'), ('pronosticos_meteorologicos', 'Pronósticos Meteorológicos'), ('cambio_climatico', 'Cambio Climático'), ('suelos', 'Suelos'), ('biodiversidad', 'Biodiversidad'), ('modelos_climaticos', 'Modelos Climáticos'), ('manejo_agua', 'Manejo de Agua'), ('variabilidad_climatica', 'Variabilidad Climática'), ('resiliencia_agricola', 'Resiliencia Agrícola'), ('riesgos_climaticos', 'Riesgos Climáticos'), ('adaptacion_clima', 'Adaptación al Clima'), ('indices_climaticos', 'Índices Climáticos'), ('escenarios_climaticos', 'Escenarios Climáticos'), ('monitoreo_climatico', 'Monitoreo Climático'), ('agricultura_sostenible', 'Agricultura Sostenible'), ('agroecologia', 'Agroecología'), ('seguridad_alimentaria', 'Seguridad Alimentaria'), ('agroforesteria', 'Agroforestería'), ('tecnologia_agricola', 'Tecnología Agrícola'), ('datos_satelitales', 'Datos Satelitales'), ('gis', 'GIS'), ('sensores_remotos', 'Sensores Remotos'), ('estaciones_meteorologicas', 'Estaciones Meteorológicas')], max_length=255, verbose_name='Palabras clave'),
        ),
    ]
