# Generated by Django 5.0.8 on 2024-09-05 14:59

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_datasetpage_keywords'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetpage',
            name='keywords',
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='Agregar múltiples palabras clave separadas por comas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Palabras clave'),
        ),
    ]
