# Generated by Django 5.0.8 on 2024-09-05 21:49

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_geodata_geo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetpage',
            name='authors',
            field=models.CharField(default='none', max_length=255, verbose_name='Autores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='data_collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la colección de datos'),
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='data_size',
            field=models.CharField(default=None, max_length=100, verbose_name='Tamaño de los datos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='data_type',
            field=models.CharField(default='preuba', max_length=100, verbose_name='Tipo de datos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='distributor',
            field=models.CharField(default='Null', max_length=255, verbose_name='Distribuidor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='file_format',
            field=models.CharField(default=5, max_length=100, verbose_name='Formato de archivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='intended_use',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Uso previsto'),
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='use_limitations',
            field=wagtail.fields.RichTextField(default='5', verbose_name='Limitaciones de Uso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='geodata',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='geo_csvs/', verbose_name='Archivo CSV de ubicaciones'),
        ),
    ]
