# Generated by Django 5.0.8 on 2024-09-06 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_institutionpage_name_customuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionpage',
            name='owner_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_institution', to=settings.AUTH_USER_MODEL, verbose_name='Representante principal'),
        ),
    ]
