# Generated by Django 5.0.8 on 2024-09-09 03:03

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_invitation_institution_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetpage',
            name='authors',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of tags.', through='home.DatasetAuthorsTag', to='taggit.Tag', verbose_name='Autores'),
        ),
    ]
