# Generated by Django 5.0.8 on 2024-09-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_datasetpage_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetpage',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='datasetfileformatstag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='datasetfileformatstag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='datasetpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='datasetpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='datasetpartnerinstitutionstag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='datasetpartnerinstitutionstag',
            name='tag',
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='file_format',
            field=models.CharField(default='', help_text='Agrega formatos separados por comas', max_length=255, verbose_name='Formato de archivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='keywords',
            field=models.CharField(default='', help_text='Agrega palabras clave separadas por comas', max_length=255, verbose_name='Palabras clave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='partner_institutions',
            field=models.CharField(default='', help_text='Agrega instituciones separados por comas', max_length=255, verbose_name='Instituciones asociadas'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DatasetAuthorsTag',
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='authors',
            field=models.CharField(default='', help_text='Agrega autores separados por comas', max_length=255, verbose_name='Autores'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DatasetFileFormatsTag',
        ),
        migrations.DeleteModel(
            name='DatasetPageTag',
        ),
        migrations.DeleteModel(
            name='DatasetPartnerInstitutionsTag',
        ),
    ]
