# Generated by Django 5.0.8 on 2024-09-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_partnerspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AboutUsPage',
        ),
        migrations.DeleteModel(
            name='PartnersPage',
        ),
    ]
