# Generated by Django 5.0.8 on 2024-09-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institutionmembership_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institution_memberships',
            field=models.ManyToManyField(related_name='members', through='institutions.InstitutionMembership', to='institutions.institutionpage', verbose_name='Instituciones donde es miembro'),
        ),
    ]
