# Generated by Django 5.0.8 on 2024-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='access_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
