# Generated by Django 5.0.8 on 2024-10-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0002_accessrequest_access_response'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessrequest',
            unique_together=set(),
        ),
    ]
